### ISSUE TITLE
pfp file type

### ISSUE THREAD

**Issue by suy0x1** [TeamSyntaEXE/Verselet#19]
in the current version users can upload any file type for the pfp, i uploaded a .py file and and took it so it doesn't matter whats the file type it will just accept it as the pfp. but when you try to update your profile it gives an error

![S](https://user-images.githubusercontent.com/73711602/137086444-10cee689-6552-4223-88c7-7bbea73b50a9.png)

it can literally shutdown the whole application.

![SS](https://user-images.githubusercontent.com/73711602/137087343-26644580-cb9b-4f75-b20d-ddba782d49f7.png)

**Comment by Maxix25** [comment]
Commit <a href="https://github.com/TeamVerselet/Verselet/commit/9641de7a811950485a2aba02639be69367f373b3">9641de7</a> fixes this error
