### ISSUE TITLE
Possible SQL Injection when searching users

### ISSUE THREAD

**Issue by Maxix25** [TeamSyntaEXE/Verselet#30]
![image](https://user-images.githubusercontent.com/68287079/160735392-bd8088d8-1fcd-4d50-b16d-e745db60110a.png)
Searching this will return all the users, which is literally like doing a ```SELECT username FROM users```, and if we have many users, it'll take a whole to load and people may be able to completely take down the website by spamming this

**Comment by suy0x1** [comment]
Not anymore
