### ISSUE TITLE
Change text input to select

### ISSUE THREAD

**Issue by Maxix25** [TeamSyntaEXE/Verselet#33]
When registering a user you need to enter the type of account, it should be personal or organization. If only those 2 types are supported then why leave an input tag instead of a select tag, it would be easier for the user to select the option instead of having to fail to see what types of accounts are available

PD: If you still want to use the input, note that it's case sensitive, so if you write "Personal" instead of "personal", it will fail too

**Comment by pavan2108** [comment]
The issue was resolved by arsh [https://github.com/TeamVerselet/Verselet/commit/a73b8f818a918e642d5bfe0c6331f322ff0def23](https://github.com/TeamVerselet/Verselet/commit/a73b8f818a918e642d5bfe0c6331f322ff0def23)
